version: '3'
services:
  db:
    image: postgres:15-alpine
    ports:
      - "5555:5432"
    restart: always
    environment:
      POSTGRES_DB: "bu"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1"

  server:
    build: .
    restart: always
    ports:
      - "8880:8880"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5555/bu
    depends_on:
      - db
